### ISSUE TITLE
Add support of label filtering in pullRequestLabeled and issueLabeled

### ISSUE THREAD

**Issue by oleg-nenashev** [boyney123/auto-comment#8]
I would like to use the bot in https://github.com/jenkinsci/jenkins in order to automate some messaging in our delivery cycles. For example, I would like the bot to post a message "The pull request is marked as ready for merge. If there is no negative feedback within 24 hours, it will be integrated towards the next weekly release" when a `ready-for-merge` label is added

It could be a syntax like:

```yaml
pullRequestLabeled: 
  label: ready-for-merge
  message: >
    The pull request is marked as ready for merge. If there is no negative feedback within 24 hours, it will be integrated towards the next weekly release
```

CC @daniel-beck @batmat
