### ISSUE TITLE
Add support for more advanced filtering

### ISSUE THREAD

**Issue by kchung** [boyney123/auto-comment#9]
Hi I was wondering if there could be support for more advanced filtering.

For example, I only want to auto comment on a `pullRequestOpened` if the `base` is equal to a certain branch. This could change how the current configuration is laid out though, spitballing: 

```yaml
pullRequestOpened: 
  base: master
  comment: >
    Thank you for raising your pull request.

    Please make sure you have followed our contributing guidelines. We will review it as soon as possible.
```
